apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "my-todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ .Release.Name }}-postgres
  replicas: 1 # PostgreSQL usually runs as a single instance for simplicity in this example
  selector:
    matchLabels:
      {{- include "my-todo-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "my-todo-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
      securityContext:
        fsGroup: 1001 # Ensure correct permissions for PostgreSQL data directory
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.postgres.persistence.storageClassName | default "standard" }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres # Headless service for StatefulSet
  labels:
    {{- include "my-todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    {{- include "my-todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  clusterIP: None # This creates a headless service
